import type { FieldSchema } from "./fields.js";
import type { Resource } from "./resource.js";
import { slugify } from "./utils.js";

function toSnakeCase(value: string): string {
  return slugify(value).replaceAll("-", "_");
}

function toTableName(resourceName: string): string {
  const base = toSnakeCase(resourceName);

  if (base.endsWith("s")) {
    return base;
  }

  return `${base}s`;
}

function toColumnName(fieldName: string): string {
  return toSnakeCase(fieldName);
}

function getSqlType(field: FieldSchema): string {
  if (field.type === "number") {
    return "REAL";
  }

  return "TEXT";
}

function getColumnDefinition(fieldName: string, field: FieldSchema): string {
  const columnName = toColumnName(fieldName);
  const sqlType = getSqlType(field);
  const required = field.required ? " NOT NULL" : "";

  return `  ${columnName} ${sqlType}${required}`;
}

export function generateDatabaseSchema(resource: Resource): string {
  const tableName = toTableName(resource.name);

  const fieldColumns = Object.entries(resource.schema)
    .map(([fieldName, field]) => getColumnDefinition(fieldName, field))
    .join(",\n");

  return `-- Generated by Paideia Framework
-- Resource: ${resource.name}

CREATE TABLE ${tableName} (
  id TEXT PRIMARY KEY,
${fieldColumns},
  created_at TEXT NOT NULL
);
`;
}

export function getTableName(resource: Resource): string {
  return toTableName(resource.name);
}
