import { posts } from "./writing/index.js";

export type SitePage = {
  path: string;
  title: string;
  description?: string;
  body: string;
  nav?: boolean;
  tokenSummary?: string;
};

export type WritingPost = {
  slug: string;
  title: string;
  label?: string;
  topics?: string[];
  description: string;
  publishedAt: string;
  body: string;
  tokenSummary: string;
};

export type SiteDefinition = {
  title: string;
  description: string;
  url?: string;
  author?: string;
  authorUrl?: string;
  language?: string;
  social?: {
    label: string;
    url: string;
  };
  sourceUrl?: string;
  faviconText?: string;
  pages: SitePage[];
  posts: WritingPost[];
};

export function defineSite(site: SiteDefinition): SiteDefinition {
  return site;
}

// The package checkout builds this small example. Real sites provide their own
// src/site.ts entry and keep their content outside the framework repository.
export const site = defineSite({
  title: "Paideia Framework Example",
  description: "A small inspectable site generated with Paideia Framework.",
  url: "https://example.com",
  author: "Paideia Framework",
  language: "en",
  sourceUrl: "https://github.com/LautaroGartner/paideia-framework",
  faviconText: "PF",
  posts,
  pages: [
    {
      path: "/",
      title: "Paideia Framework Example",
      description: "A small inspectable site generated with Paideia Framework.",
      body: "",
      nav: false,
      tokenSummary: "Example article index generated by Paideia Framework.",
    },
    {
      path: "/about",
      title: "About",
      description: "About this Paideia Framework example.",
      body: `
This is the framework's deliberately small example site.

Application content belongs in the application repository. Paideia provides the build, runtime identity, diagnostics, and inspectable generated artifacts.
`,
      nav: true,
      tokenSummary: "About the example site bundled with Paideia Framework.",
    },
  ],
});
