import type {
  SiteDefinition,
  SitePage,
  WritingPost,
} from "./site.js";
import { config } from "./config.js";
import { escapeHtml } from "./utils.js";
import { FRAMEWORK_VERSION } from "./version.js";

const AUTHOR_NAME = "Lautaro Gärtner";
const AUTHOR_USERNAME = "@lautyxgr";
const X_PROFILE_URL = "https://x.com/lautyxgr";
const SOURCE_URL = "https://github.com/LautaroGartner/paideia-framework";

function normalizePath(pagePath: string): string {
  if (pagePath === "/") {
    return "/";
  }

  return `/${pagePath.replace(/^\/+|\/+$/g, "")}`;
}

function sortPosts(posts: WritingPost[]): WritingPost[] {
  return [...posts].sort((left, right) =>
    right.publishedAt.localeCompare(left.publishedAt)
  );
}

function siteLanguage(site: SiteDefinition): string {
  return site.language ?? "en";
}

function canonicalUrl(
  site: SiteDefinition,
  pagePath: string
): string | null {
  if (!site.url) {
    return null;
  }

  const base = site.url.replace(/\/+$/g, "");
  const normalized = normalizePath(pagePath);

  if (normalized === "/") {
    return `${base}/`;
  }

  return `${base}${normalized}`;
}

function renderHead(options: {
  site: SiteDefinition;
  path: string;
  title: string;
  description: string;
}): string {
  const canonical = canonicalUrl(
    options.site,
    options.path
  );
  const author = options.site.author
    ? `\n    <meta name="author" content="${escapeHtml(options.site.author)}">`
    : "";
  const canonicalLink = canonical
    ? `\n    <link rel="canonical" href="${escapeHtml(canonical)}">`
    : "";

  return `<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(options.title)}</title>
    <meta name="description" content="${escapeHtml(options.description)}">
    <link rel="icon" href="/favicon.svg" type="image/svg+xml">${author}${canonicalLink}`;
}

function pageOutputPath(page: SitePage): string {
  const normalized = normalizePath(page.path);

  if (normalized === "/") {
    return "index.html";
  }

  return `${normalized.slice(1)}/index.html`;
}

function postPath(post: WritingPost): string {
  return `/${post.slug}`;
}

function postOutputPath(post: WritingPost): string {
  return `${post.slug}/index.html`;
}

function formatDate(value: string): string {
  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(`${value}T00:00:00Z`));
}

function relativePublishedAt(value: string): string {
  const publishedAt = new Date(`${value}T00:00:00Z`);
  const now = new Date();
  const day = 24 * 60 * 60 * 1000;
  const today = Date.UTC(
    now.getUTCFullYear(),
    now.getUTCMonth(),
    now.getUTCDate()
  );
  const publishedDay = Date.UTC(
    publishedAt.getUTCFullYear(),
    publishedAt.getUTCMonth(),
    publishedAt.getUTCDate()
  );
  const days = Math.floor((today - publishedDay) / day);

  if (days === 0) {
    return "today";
  }

  if (days < 0) {
    return "soon";
  }

  if (days < 30) {
    return `${days}d ago`;
  }

  const months = Math.floor(days / 30);

  if (months < 12) {
    return `${months}mo ago`;
  }

  return `${Math.floor(months / 12)}y ago`;
}

function postLabel(post: WritingPost): string {
  return post.label ?? "Paideia note";
}

function renderPostTopics(post: WritingPost): string {
  if (!post.topics || post.topics.length === 0) {
    return "";
  }

  return `<p class="post-topics">${post.topics
    .map((topic) => escapeHtml(topic))
    .join(" / ")}</p>`;
}

function renderHeader(
  site: SiteDefinition,
  currentPath: string
): string {
  const label = site.author ?? AUTHOR_NAME;
  const brand =
    normalizePath(currentPath) === "/"
      ? `<span class="brand">${escapeHtml(label)}</span>`
      : `<a class="brand" href="/">${escapeHtml(label)}</a>`;

  return `<header>
        ${brand}
        <nav aria-label="Site">
          <a href="/about">About</a>
          <a href="${escapeHtml(X_PROFILE_URL)}" rel="me">𝕏 Follow me</a>
        </nav>
      </header>`;
}

function renderFooter(): string {
  return `<footer>
        <span>${escapeHtml(AUTHOR_NAME)} (<a href="${escapeHtml(X_PROFILE_URL)}" rel="me">${escapeHtml(AUTHOR_USERNAME)}</a>)</span>
        <span>Generated by Paideia Framework v${escapeHtml(FRAMEWORK_VERSION)}.</span>
        <a href="${escapeHtml(SOURCE_URL)}">Source</a>
      </footer>`;
}

function renderAgentFileLinks(): string {
  return `<p class="agent-files">
          <a href="/system.json">system.json</a>
          <a href="/runtime.json">runtime.json</a>
          <a href="/context.json">context.json</a>
          <a href="/llms.txt">llms.txt</a>
        </p>`;
}

function renderBody(value: string): string {
  return value
    .trim()
    .split(/\n{2,}/)
    .map(
      (paragraph) =>
        `<p>${escapeHtml(paragraph.replace(/\s*\n\s*/g, " "))}</p>`
    )
    .join("\n        ");
}

function renderPostList(posts: WritingPost[], options: {
  heading?: string;
  limit?: number;
} = {}): string {
  const orderedPosts = sortPosts(posts);

  if (orderedPosts.length === 0) {
    return `
        <section class="post-list" aria-label="Writing">
          <p class="empty-state">No writing published yet.</p>
        </section>`;
  }

  const visiblePosts =
    typeof options.limit === "number"
      ? orderedPosts.slice(0, options.limit)
      : orderedPosts;
  const heading = options.heading
    ? `<h2>${escapeHtml(options.heading)}</h2>`
    : "";

  return `
        <section class="post-list" aria-label="Writing">
          ${heading}
          ${visiblePosts
            .map(
              (post) => `<article class="post-item">
            <time datetime="${escapeHtml(post.publishedAt)}">${escapeHtml(formatDate(post.publishedAt))}</time>
            <div>
              <p class="post-kicker">${escapeHtml(postLabel(post))}</p>
              <h2><a href="${escapeHtml(postPath(post))}">${escapeHtml(post.title)}</a></h2>
              ${renderPostTopics(post)}
            </div>
          </article>`
            )
            .join("\n          ")}
        </section>`;
}

export function generateFaviconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <circle cx="32" cy="32" r="30" fill="#fbfaf7"/>
  <circle cx="32" cy="32" r="29" fill="none" stroke="#e8e2d8" stroke-width="2"/>
  <text x="32" y="40" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="23" font-weight="700" fill="#5f6f52">LG</text>
</svg>
`;
}

export function getSiteOutputPath(page: SitePage): string {
  return pageOutputPath(page);
}

export function getPostOutputPath(post: WritingPost): string {
  return postOutputPath(post);
}

export function generateSitePage(
  site: SiteDefinition,
  page: SitePage
): string {
  const title =
    page.path === "/"
      ? site.title
      : `${page.title} - ${AUTHOR_NAME}`;

  const description =
    page.description ?? site.description;
  const isHome = normalizePath(page.path) === "/";
  const isAbout = normalizePath(page.path) === "/about";
  const pageBody = isHome
    ? ""
    : `<h1>${escapeHtml(page.title)}</h1>
        ${renderBody(page.body)}
        ${isAbout ? renderAgentFileLinks() : ""}`;
  const postList =
    normalizePath(page.path) === "/"
      ? renderPostList(site.posts)
      : "";

  return `<!doctype html>
<html lang="${escapeHtml(siteLanguage(site))}">
  <head>
    ${renderHead({
      site,
      path: page.path,
      title,
      description,
    })}
    <style>
      :root {
        --accent: #5f6f52;
        --bg: #fbfaf7;
        --line: #e8e2d8;
        --muted: #6f6a61;
        --text: #151515;
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: var(--bg);
        color: var(--text);
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 36px 0 64px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        padding-bottom: 10px;
      }

      header a,
      header .brand {
        color: inherit;
        font-size: 0.9rem;
        font-weight: 600;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: var(--muted);
        font-weight: 500;
      }

      main {
        padding-top: 64px;
      }

      h1 {
        margin: 0;
        max-width: 680px;
        font-size: clamp(1.8rem, 5vw, 3rem);
        line-height: 1;
        letter-spacing: 0;
      }

      p {
        max-width: 620px;
        margin: 22px 0 0;
        color: var(--text);
        font-size: 1rem;
        line-height: 1.75;
      }

      .post-list {
        display: grid;
        gap: 24px;
        margin-top: 0;
      }

      .post-list > h2 {
        margin: 0;
        font-size: 1rem;
        letter-spacing: 0;
      }

      .empty-state {
        margin-top: 0;
        font-size: 1rem;
      }

      .post-item {
        display: grid;
        grid-template-columns: 112px minmax(0, 1fr);
        gap: 18px;
        align-items: start;
      }

      time {
        color: var(--muted);
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 0.78rem;
        white-space: nowrap;
      }

      .post-kicker {
        margin: 0 0 5px;
        color: var(--accent);
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 0.72rem;
        letter-spacing: 0.08em;
        line-height: 1.4;
        text-transform: uppercase;
      }

      h2 {
        margin: 0;
        font-size: 0.98rem;
        font-weight: 560;
        letter-spacing: 0;
        line-height: 1.45;
      }

      h2 a {
        color: inherit;
        text-decoration: none;
      }

      a:hover {
        color: var(--accent);
        text-decoration: underline;
        text-underline-offset: 3px;
      }

      .post-topics {
        margin: 5px 0 0;
        color: var(--muted);
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 0.78rem;
        line-height: 1.5;
      }

      .agent-files {
        display: flex;
        flex-wrap: wrap;
        gap: 12px;
        color: var(--muted);
        font-size: 0.9rem;
      }

      .agent-files a {
        color: inherit;
      }

      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 18px;
        flex-wrap: wrap;
        margin-top: 92px;
        border-top: 1px solid var(--line);
        padding-top: 18px;
        color: var(--muted);
        font-size: 0.88rem;
      }

      footer nav {
        gap: 12px;
      }

      footer a {
        color: inherit;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 24px;
        }

        header {
          gap: 16px;
        }

        main {
          padding-top: 48px;
        }

        .post-item {
          grid-template-columns: 1fr;
          gap: 6px;
        }

        footer {
          align-items: flex-start;
          flex-direction: column;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      ${renderHeader(site, page.path)}
      <main>
        ${pageBody}
${postList}
      </main>
      ${renderFooter()}
    </div>
  </body>
</html>
`;
}

export function generatePostPage(
  site: SiteDefinition,
  post: WritingPost
): string {
  return `<!doctype html>
<html lang="${escapeHtml(siteLanguage(site))}">
  <head>
    ${renderHead({
      site,
      path: postPath(post),
      title: `${post.title} - ${AUTHOR_NAME}`,
      description: post.description,
    })}
    <style>
      :root {
        --accent: #5f6f52;
        --bg: #fbfaf7;
        --line: #e8e2d8;
        --muted: #6f6a61;
        --text: #151515;
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: var(--bg);
        color: var(--text);
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 36px 0 64px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        padding-bottom: 10px;
      }

      header a,
      header .brand,
      nav a {
        color: inherit;
        font-size: 0.9rem;
        font-weight: 600;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: var(--muted);
        font-weight: 500;
      }

      main {
        padding-top: 64px;
      }

      .meta {
        color: var(--muted);
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 0.78rem;
        line-height: 1.5;
      }

      .meta a {
        color: inherit;
      }

      .post-kicker {
        margin: 0 0 8px;
        color: var(--accent);
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 0.72rem;
        letter-spacing: 0.08em;
        line-height: 1.4;
        text-transform: uppercase;
      }

      h1 {
        margin: 12px 0 0;
        max-width: 680px;
        font-size: clamp(2rem, 7vw, 3.4rem);
        line-height: 1;
        letter-spacing: 0;
      }

      .description {
        max-width: 620px;
        margin: 22px 0 0;
        color: var(--text);
        font-size: 1rem;
        line-height: 1.7;
      }

      .post-body {
        margin-top: 46px;
      }

      .post-body p {
        max-width: 640px;
        margin: 0 0 24px;
        color: var(--text);
        font-size: 1.03rem;
        line-height: 1.8;
      }

      a:hover {
        color: var(--accent);
        text-decoration: underline;
        text-underline-offset: 3px;
      }

      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 18px;
        flex-wrap: wrap;
        margin-top: 92px;
        border-top: 1px solid var(--line);
        padding-top: 18px;
        color: var(--muted);
        font-size: 0.88rem;
      }

      footer nav {
        gap: 12px;
      }

      footer a {
        color: inherit;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 24px;
        }

        header {
          gap: 16px;
        }

        main {
          padding-top: 48px;
        }

        footer {
          align-items: flex-start;
          flex-direction: column;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      ${renderHeader(site, postPath(post))}
      <main>
        <p class="post-kicker">${escapeHtml(postLabel(post))}</p>
        <div class="meta"><a href="${escapeHtml(X_PROFILE_URL)}" rel="me">${escapeHtml(AUTHOR_USERNAME)}</a> | <time datetime="${escapeHtml(post.publishedAt)}">${escapeHtml(formatDate(post.publishedAt))}</time> | ${escapeHtml(relativePublishedAt(post.publishedAt))}</div>
        <h1>${escapeHtml(post.title)}</h1>
        <p class="description">${escapeHtml(post.description)}</p>
        <div class="post-body">
          ${renderBody(post.body)}
        </div>
      </main>
      ${renderFooter()}
    </div>
  </body>
</html>
`;
}

export function generateNotFoundPage(site: SiteDefinition): string {
  return `<!doctype html>
<html lang="${escapeHtml(siteLanguage(site))}">
  <head>
    ${renderHead({
      site,
      path: "/404",
      title: `Page not found - ${site.title}`,
      description: "The requested page could not be found.",
    })}
    <style>
      :root {
        --accent: #5f6f52;
        --bg: #fbfaf7;
        --line: #e8e2d8;
        --muted: #6f6a61;
        --text: #151515;
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: var(--bg);
        color: var(--text);
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 36px 0 64px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        padding-bottom: 10px;
      }

      header a,
      header .brand,
      nav a {
        color: inherit;
        font-size: 0.9rem;
        font-weight: 600;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: var(--muted);
        font-weight: 500;
      }

      main {
        padding-top: 64px;
      }

      h1 {
        margin: 0;
        max-width: 680px;
        font-size: clamp(1.8rem, 5vw, 3rem);
        line-height: 1;
        letter-spacing: 0;
      }

      p {
        max-width: 620px;
        margin: 26px 0 0;
        color: var(--text);
        font-size: 1rem;
        line-height: 1.7;
      }

      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 18px;
        flex-wrap: wrap;
        margin-top: 92px;
        border-top: 1px solid var(--line);
        padding-top: 18px;
        color: var(--muted);
        font-size: 0.88rem;
      }

      footer nav {
        gap: 12px;
      }

      footer a {
        color: inherit;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 24px;
        }

        header {
          gap: 16px;
        }

        main {
          padding-top: 48px;
        }

        footer {
          align-items: flex-start;
          flex-direction: column;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      ${renderHeader(site, "/404")}
      <main>
        <h1>Page not found</h1>
        <p>The page you are looking for does not exist yet.</p>
      </main>
      ${renderFooter()}
    </div>
  </body>
</html>
`;
}

export function generateSiteManifest(site: SiteDefinition): string {
  return generateSiteManifestWithCapabilities(site, []);
}

export function generateSiteManifestWithCapabilities(
  site: SiteDefinition,
  capabilities: string[]
): string {
  const orderedPosts = sortPosts(site.posts);

  const manifest = {
    framework: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
      mode: config.mode,
    },
    capabilities,
    site: {
      title: site.title,
      description: site.description,
      url: site.url ?? null,
      author: site.author ?? null,
      language: siteLanguage(site),
      pages: site.pages.map((page) => ({
        path: normalizePath(page.path),
        canonical: canonicalUrl(site, page.path),
        title: page.title,
        description: page.description ?? null,
        nav: page.nav !== false,
        tokenSummary: page.tokenSummary ?? null,
        output: pageOutputPath(page),
      })),
      posts: orderedPosts.map((post) => ({
        slug: post.slug,
        path: postPath(post),
        canonical: canonicalUrl(site, postPath(post)),
        title: post.title,
        label: postLabel(post),
        topics: post.topics ?? [],
        description: post.description,
        publishedAt: post.publishedAt,
        tokenSummary: post.tokenSummary,
        output: postOutputPath(post),
      })),
    },
    runtime: {
      target: "static-site",
      generation: {
        strategy: "static",
        output: "dist",
      },
      generatedArtifacts: [
        "404.html",
        "favicon.svg",
        "pages",
        "posts",
        "system.json",
        "runtime.json",
        "llms.txt",
        "context.json",
      ],
    },
    trust: {
      siteContractExplicit: true,
      generatedArtifactsInspectable: true,
      tokenFriendlyContextAvailable: true,
    },
  };

  return JSON.stringify(manifest, null, 2);
}

export function generateRuntimeIdentity(
  site: SiteDefinition,
  options: {
    artifactCount: number;
    artifacts: Array<{
      path: string;
      kind: string;
      bytes: number;
    }>;
    buildId: string;
    capabilities: string[];
    generatedAt: string;
    mode: "development" | "production";
  }
): string {
  const identity = {
    framework: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
    },
    build: {
      id: options.buildId,
      generatedAt: options.generatedAt,
      mode: options.mode,
      artifactCount: options.artifactCount,
    },
    capabilities: options.capabilities,
    artifacts: options.artifacts,
    site: {
      pages: site.pages.length,
      posts: site.posts.length,
    },
    runtime: {
      inspectable: true,
      normalizedManifest: true,
      agentReadable: true,
    },
  };

  return JSON.stringify(identity, null, 2);
}

export function generateLlmsText(site: SiteDefinition): string {
  const orderedPosts = sortPosts(site.posts);
  const pages = site.pages
    .map((page) => {
      const summary = page.tokenSummary
        ? ` - ${page.tokenSummary}`
        : "";
      return `- ${page.title}: ${normalizePath(page.path)}${summary}`;
    })
    .join("\n");
  const posts = orderedPosts
    .map(
      (post) =>
        `- ${post.title}: ${postPath(post)} - ${post.tokenSummary}`
    )
    .join("\n");

  return `# ${site.title}

This site is generated by Paideia Framework.

Useful agent entrypoints:
- /system.json - runtime and site contract
- /runtime.json - runtime identity and build metadata
- /context.json - compressed site map and summaries
- /llms.txt - agent guidance

## Site

${site.description}
${site.url ? `\nCanonical site URL: ${site.url}` : ""}
${site.author ? `\nAuthor: ${site.author}` : ""}
Language: ${siteLanguage(site)}

## Pages

${pages}

## Writing

${posts}

## Generated By

Paideia Framework v${FRAMEWORK_VERSION}
`;
}

export function generateContextJson(site: SiteDefinition): string {
  const orderedPosts = sortPosts(site.posts);
  const latestPost = orderedPosts[0] ?? null;

  const context = {
    site: {
      title: site.title,
      description: site.description,
      url: site.url ?? null,
      author: site.author ?? null,
      language: siteLanguage(site),
    },
    pages: site.pages.map((page) => ({
      path: normalizePath(page.path),
      canonical: canonicalUrl(site, page.path),
      title: page.title,
      description:
        page.description ?? site.description,
      tokenSummary:
        page.tokenSummary ?? page.body,
    })),
    posts: orderedPosts.map((post) => ({
      slug: post.slug,
      path: postPath(post),
      canonical: canonicalUrl(site, postPath(post)),
      title: post.title,
      label: postLabel(post),
      topics: post.topics ?? [],
      publishedAt: post.publishedAt,
      tokenSummary: post.tokenSummary,
    })),
    writing: {
      postCount: orderedPosts.length,
      latestPost: latestPost?.slug ?? null,
    },
    generatedBy: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
    },
  };

  return JSON.stringify(context, null, 2);
}
