import type {
  SiteDefinition,
  SitePage,
} from "./site.js";
import { config } from "./config.js";
import { escapeHtml } from "./utils.js";
import { FRAMEWORK_VERSION } from "./version.js";

function normalizePath(pagePath: string): string {
  if (pagePath === "/") {
    return "/";
  }

  return `/${pagePath.replace(/^\/+|\/+$/g, "")}`;
}

function pageOutputPath(page: SitePage): string {
  const normalized = normalizePath(page.path);

  if (normalized === "/") {
    return "index.html";
  }

  return `${normalized.slice(1)}/index.html`;
}

function renderNavigation(pages: SitePage[]): string {
  return `
        <nav aria-label="Site">
          ${pages
            .map((page) => {
              const href = normalizePath(page.path);
              return `<a href="${escapeHtml(href)}">${escapeHtml(page.title)}</a>`;
            })
            .join("\n          ")}
        </nav>`;
}

export function getSiteOutputPath(page: SitePage): string {
  return pageOutputPath(page);
}

export function generateSitePage(
  site: SiteDefinition,
  page: SitePage
): string {
  const title =
    page.path === "/"
      ? site.title
      : `${page.title} - ${site.title}`;

  const description =
    page.description ?? site.description;
  const navPages = site.pages.filter(
    (item) => item.nav !== false
  );

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(description)}">
    <style>
      :root {
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: #f7f6f2;
        color: #191816;
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 42px 0 72px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        border-bottom: 1px solid #dedbd2;
        padding-bottom: 18px;
      }

      header a {
        color: inherit;
        font-size: 0.92rem;
        font-weight: 700;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: #5f5a50;
        font-weight: 650;
      }

      main {
        padding-top: 78px;
      }

      h1 {
        margin: 0;
        max-width: 680px;
        font-size: clamp(2.4rem, 7vw, 4.7rem);
        line-height: 0.96;
        letter-spacing: 0;
      }

      p {
        max-width: 620px;
        margin: 26px 0 0;
        color: #4f4a43;
        font-size: 1.15rem;
        line-height: 1.7;
      }

      footer {
        margin-top: 92px;
        border-top: 1px solid #dedbd2;
        padding-top: 18px;
        color: #716b61;
        font-size: 0.88rem;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 26px;
        }

        header {
          align-items: flex-start;
          flex-direction: column;
        }

        main {
          padding-top: 54px;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      <header>
        <a href="/">${escapeHtml(site.title)}</a>
${renderNavigation(navPages)}
      </header>
      <main>
        <h1>${escapeHtml(page.title)}</h1>
        <p>${escapeHtml(page.body)}</p>
      </main>
      <footer>Generated by Paideia Framework v${escapeHtml(FRAMEWORK_VERSION)}.</footer>
    </div>
  </body>
</html>
`;
}

export function generateSiteManifest(site: SiteDefinition): string {
  const manifest = {
    framework: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
      mode: config.mode,
    },
    site: {
      title: site.title,
      description: site.description,
      pages: site.pages.map((page) => ({
        path: normalizePath(page.path),
        title: page.title,
        description: page.description ?? null,
        nav: page.nav !== false,
        tokenSummary: page.tokenSummary ?? null,
        output: pageOutputPath(page),
      })),
    },
    runtime: {
      target: "static-site",
      generation: {
        strategy: "static",
        output: "dist",
      },
      generatedArtifacts: [
        "pages",
        "system.json",
        "llms.txt",
        "context.json",
      ],
    },
    trust: {
      siteContractExplicit: true,
      generatedArtifactsInspectable: true,
      tokenFriendlyContextAvailable: true,
    },
  };

  return JSON.stringify(manifest, null, 2);
}

export function generateLlmsText(site: SiteDefinition): string {
  const pages = site.pages
    .map((page) => {
      const summary = page.tokenSummary
        ? ` - ${page.tokenSummary}`
        : "";
      return `- ${page.title}: ${normalizePath(page.path)}${summary}`;
    })
    .join("\n");

  return `# ${site.title}

This site is generated by Paideia Framework.

Useful agent entrypoints:
- /system.json - runtime and site contract
- /context.json - compressed site map and summaries
- /llms.txt - agent guidance

## Site

${site.description}

## Pages

${pages}

## Generated By

Paideia Framework v${FRAMEWORK_VERSION}
`;
}

export function generateContextJson(site: SiteDefinition): string {
  const context = {
    site: {
      title: site.title,
      description: site.description,
    },
    pages: site.pages.map((page) => ({
      path: normalizePath(page.path),
      title: page.title,
      description:
        page.description ?? site.description,
      tokenSummary:
        page.tokenSummary ?? page.body,
    })),
    generatedBy: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
    },
  };

  return JSON.stringify(context, null, 2);
}
