import type {
  SiteDefinition,
  SitePage,
  WritingPost,
} from "./site.js";
import { config } from "./config.js";
import { escapeHtml } from "./utils.js";
import { FRAMEWORK_VERSION } from "./version.js";

function normalizePath(pagePath: string): string {
  if (pagePath === "/") {
    return "/";
  }

  return `/${pagePath.replace(/^\/+|\/+$/g, "")}`;
}

function sortPosts(posts: WritingPost[]): WritingPost[] {
  return [...posts].sort((left, right) =>
    right.publishedAt.localeCompare(left.publishedAt)
  );
}

function siteLanguage(site: SiteDefinition): string {
  return site.language ?? "en";
}

function canonicalUrl(
  site: SiteDefinition,
  pagePath: string
): string | null {
  if (!site.url) {
    return null;
  }

  const base = site.url.replace(/\/+$/g, "");
  const normalized = normalizePath(pagePath);

  if (normalized === "/") {
    return `${base}/`;
  }

  return `${base}${normalized}`;
}

function renderHead(options: {
  site: SiteDefinition;
  path: string;
  title: string;
  description: string;
}): string {
  const canonical = canonicalUrl(
    options.site,
    options.path
  );
  const author = options.site.author
    ? `\n    <meta name="author" content="${escapeHtml(options.site.author)}">`
    : "";
  const canonicalLink = canonical
    ? `\n    <link rel="canonical" href="${escapeHtml(canonical)}">`
    : "";

  return `<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(options.title)}</title>
    <meta name="description" content="${escapeHtml(options.description)}">${author}${canonicalLink}`;
}

function pageOutputPath(page: SitePage): string {
  const normalized = normalizePath(page.path);

  if (normalized === "/") {
    return "index.html";
  }

  return `${normalized.slice(1)}/index.html`;
}

function postPath(post: WritingPost): string {
  return `/writing/${post.slug}`;
}

function postOutputPath(post: WritingPost): string {
  return `writing/${post.slug}/index.html`;
}

function renderNavigation(pages: SitePage[]): string {
  return `
        <nav aria-label="Site">
          ${pages
            .map((page) => {
              const href = normalizePath(page.path);
              return `<a href="${escapeHtml(href)}">${escapeHtml(page.title)}</a>`;
            })
            .join("\n          ")}
        </nav>`;
}

function renderFooter(): string {
  return `<footer>
        <span>Generated by Paideia Framework v${escapeHtml(FRAMEWORK_VERSION)}.</span>
        <nav aria-label="Agent files">
          <a href="/system.json">system.json</a>
          <a href="/runtime.json">runtime.json</a>
          <a href="/context.json">context.json</a>
          <a href="/llms.txt">llms.txt</a>
        </nav>
      </footer>`;
}

function renderBody(value: string): string {
  return value
    .trim()
    .split(/\n{2,}/)
    .map(
      (paragraph) =>
        `<p>${escapeHtml(paragraph.replace(/\s*\n\s*/g, " "))}</p>`
    )
    .join("\n        ");
}

function renderPostList(posts: WritingPost[], options: {
  heading?: string;
  limit?: number;
} = {}): string {
  const orderedPosts = sortPosts(posts);

  if (orderedPosts.length === 0) {
    return `
        <section class="post-list" aria-label="Writing">
          <p class="empty-state">No writing published yet.</p>
        </section>`;
  }

  const visiblePosts =
    typeof options.limit === "number"
      ? orderedPosts.slice(0, options.limit)
      : orderedPosts;
  const heading = options.heading
    ? `<h2>${escapeHtml(options.heading)}</h2>`
    : "";

  return `
        <section class="post-list" aria-label="Writing">
          ${heading}
          ${visiblePosts
            .map(
              (post) => `<article>
            <time datetime="${escapeHtml(post.publishedAt)}">${escapeHtml(post.publishedAt)}</time>
            <h2><a href="${escapeHtml(postPath(post))}">${escapeHtml(post.title)}</a></h2>
            <p>${escapeHtml(post.description)}</p>
          </article>`
            )
            .join("\n          ")}
        </section>`;
}

export function getSiteOutputPath(page: SitePage): string {
  return pageOutputPath(page);
}

export function getPostOutputPath(post: WritingPost): string {
  return postOutputPath(post);
}

export function generateSitePage(
  site: SiteDefinition,
  page: SitePage
): string {
  const title =
    page.path === "/"
      ? site.title
      : `${page.title} - ${site.title}`;

  const description =
    page.description ?? site.description;
  const navPages = site.pages.filter(
    (item) => item.nav !== false
  );
  const writingList =
    normalizePath(page.path) === "/writing"
      ? renderPostList(site.posts)
      : "";
  const latestWriting =
    normalizePath(page.path) === "/"
      ? renderPostList(site.posts, {
          heading: "Latest writing",
          limit: 3,
        })
      : "";

  return `<!doctype html>
<html lang="${escapeHtml(siteLanguage(site))}">
  <head>
    ${renderHead({
      site,
      path: page.path,
      title,
      description,
    })}
    <style>
      :root {
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: #f7f6f2;
        color: #191816;
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 42px 0 72px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        border-bottom: 1px solid #dedbd2;
        padding-bottom: 18px;
      }

      header a {
        color: inherit;
        font-size: 0.92rem;
        font-weight: 700;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: #5f5a50;
        font-weight: 650;
      }

      main {
        padding-top: 78px;
      }

      h1 {
        margin: 0;
        max-width: 680px;
        font-size: clamp(2.4rem, 7vw, 4.7rem);
        line-height: 0.96;
        letter-spacing: 0;
      }

      p {
        max-width: 620px;
        margin: 26px 0 0;
        color: #4f4a43;
        font-size: 1.15rem;
        line-height: 1.7;
      }

      .post-list {
        display: grid;
        gap: 22px;
        margin-top: 44px;
      }

      .post-list > h2 {
        margin: 0;
        font-size: 1rem;
        letter-spacing: 0;
      }

      .empty-state {
        margin-top: 0;
        font-size: 1rem;
      }

      article {
        border-top: 1px solid #dedbd2;
        padding-top: 22px;
      }

      time {
        color: #716b61;
        font-size: 0.88rem;
      }

      h2 {
        margin: 8px 0 0;
        font-size: 1.35rem;
        letter-spacing: 0;
      }

      h2 a {
        color: inherit;
        text-decoration: none;
      }

      article p {
        margin-top: 10px;
        font-size: 1rem;
      }

      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 18px;
        flex-wrap: wrap;
        margin-top: 92px;
        border-top: 1px solid #dedbd2;
        padding-top: 18px;
        color: #716b61;
        font-size: 0.88rem;
      }

      footer nav {
        gap: 12px;
      }

      footer a {
        color: inherit;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 26px;
        }

        header {
          align-items: flex-start;
          flex-direction: column;
        }

        main {
          padding-top: 54px;
        }

        footer {
          align-items: flex-start;
          flex-direction: column;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      <header>
        <a href="/">${escapeHtml(site.title)}</a>
${renderNavigation(navPages)}
      </header>
      <main>
        <h1>${escapeHtml(page.title)}</h1>
        <p>${escapeHtml(page.body)}</p>
${latestWriting}
${writingList}
      </main>
      ${renderFooter()}
    </div>
  </body>
</html>
`;
}

export function generatePostPage(
  site: SiteDefinition,
  post: WritingPost
): string {
  const navPages = site.pages.filter(
    (item) => item.nav !== false
  );

  return `<!doctype html>
<html lang="${escapeHtml(siteLanguage(site))}">
  <head>
    ${renderHead({
      site,
      path: postPath(post),
      title: `${post.title} - ${site.title}`,
      description: post.description,
    })}
    <style>
      :root {
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: #f7f6f2;
        color: #191816;
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 42px 0 72px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        border-bottom: 1px solid #dedbd2;
        padding-bottom: 18px;
      }

      header a,
      nav a {
        color: inherit;
        font-size: 0.92rem;
        font-weight: 700;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: #5f5a50;
        font-weight: 650;
      }

      main {
        padding-top: 78px;
      }

      time {
        color: #716b61;
        font-size: 0.92rem;
      }

      h1 {
        margin: 14px 0 0;
        max-width: 680px;
        font-size: clamp(2.4rem, 7vw, 4.7rem);
        line-height: 0.96;
        letter-spacing: 0;
      }

      .description {
        max-width: 620px;
        margin: 24px 0 0;
        color: #4f4a43;
        font-size: 1.15rem;
        line-height: 1.7;
      }

      .post-body {
        margin-top: 50px;
      }

      .post-body p {
        max-width: 640px;
        margin: 0 0 24px;
        color: #292622;
        font-size: 1.1rem;
        line-height: 1.8;
      }

      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 18px;
        flex-wrap: wrap;
        margin-top: 92px;
        border-top: 1px solid #dedbd2;
        padding-top: 18px;
        color: #716b61;
        font-size: 0.88rem;
      }

      footer nav {
        gap: 12px;
      }

      footer a {
        color: inherit;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 26px;
        }

        header {
          align-items: flex-start;
          flex-direction: column;
        }

        main {
          padding-top: 54px;
        }

        footer {
          align-items: flex-start;
          flex-direction: column;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      <header>
        <a href="/">${escapeHtml(site.title)}</a>
${renderNavigation(navPages)}
      </header>
      <main>
        <time datetime="${escapeHtml(post.publishedAt)}">${escapeHtml(post.publishedAt)}</time>
        <h1>${escapeHtml(post.title)}</h1>
        <p class="description">${escapeHtml(post.description)}</p>
        <div class="post-body">
          ${renderBody(post.body)}
        </div>
      </main>
      ${renderFooter()}
    </div>
  </body>
</html>
`;
}

export function generateNotFoundPage(site: SiteDefinition): string {
  const navPages = site.pages.filter(
    (item) => item.nav !== false
  );

  return `<!doctype html>
<html lang="${escapeHtml(siteLanguage(site))}">
  <head>
    ${renderHead({
      site,
      path: "/404",
      title: `Page not found - ${site.title}`,
      description: "The requested page could not be found.",
    })}
    <style>
      :root {
        color-scheme: light;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: #f7f6f2;
        color: #191816;
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
      }

      .shell {
        width: min(760px, calc(100vw - 40px));
        margin: 0 auto;
        padding: 42px 0 72px;
      }

      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
        border-bottom: 1px solid #dedbd2;
        padding-bottom: 18px;
      }

      header a,
      nav a {
        color: inherit;
        font-size: 0.92rem;
        font-weight: 700;
        text-decoration: none;
      }

      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 14px;
      }

      nav a {
        color: #5f5a50;
        font-weight: 650;
      }

      main {
        padding-top: 78px;
      }

      h1 {
        margin: 0;
        max-width: 680px;
        font-size: clamp(2.4rem, 7vw, 4.7rem);
        line-height: 0.96;
        letter-spacing: 0;
      }

      p {
        max-width: 620px;
        margin: 26px 0 0;
        color: #4f4a43;
        font-size: 1.15rem;
        line-height: 1.7;
      }

      footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 18px;
        flex-wrap: wrap;
        margin-top: 92px;
        border-top: 1px solid #dedbd2;
        padding-top: 18px;
        color: #716b61;
        font-size: 0.88rem;
      }

      footer nav {
        gap: 12px;
      }

      footer a {
        color: inherit;
      }

      @media (max-width: 640px) {
        .shell {
          width: min(100vw - 28px, 760px);
          padding-top: 26px;
        }

        header {
          align-items: flex-start;
          flex-direction: column;
        }

        main {
          padding-top: 54px;
        }

        footer {
          align-items: flex-start;
          flex-direction: column;
        }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      <header>
        <a href="/">${escapeHtml(site.title)}</a>
${renderNavigation(navPages)}
      </header>
      <main>
        <h1>Page not found</h1>
        <p>The page you are looking for does not exist yet.</p>
      </main>
      ${renderFooter()}
    </div>
  </body>
</html>
`;
}

export function generateSiteManifest(site: SiteDefinition): string {
  const orderedPosts = sortPosts(site.posts);

  const manifest = {
    framework: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
      mode: config.mode,
    },
    site: {
      title: site.title,
      description: site.description,
      url: site.url ?? null,
      author: site.author ?? null,
      language: siteLanguage(site),
      pages: site.pages.map((page) => ({
        path: normalizePath(page.path),
        canonical: canonicalUrl(site, page.path),
        title: page.title,
        description: page.description ?? null,
        nav: page.nav !== false,
        tokenSummary: page.tokenSummary ?? null,
        output: pageOutputPath(page),
      })),
      posts: orderedPosts.map((post) => ({
        slug: post.slug,
        path: postPath(post),
        canonical: canonicalUrl(site, postPath(post)),
        title: post.title,
        description: post.description,
        publishedAt: post.publishedAt,
        tokenSummary: post.tokenSummary,
        output: postOutputPath(post),
      })),
    },
    runtime: {
      target: "static-site",
      generation: {
        strategy: "static",
        output: "dist",
      },
      generatedArtifacts: [
        "404.html",
        "pages",
        "posts",
        "system.json",
        "runtime.json",
        "llms.txt",
        "context.json",
      ],
    },
    trust: {
      siteContractExplicit: true,
      generatedArtifactsInspectable: true,
      tokenFriendlyContextAvailable: true,
    },
  };

  return JSON.stringify(manifest, null, 2);
}

export function generateRuntimeIdentity(
  site: SiteDefinition,
  options: {
    artifactCount: number;
    artifacts: Array<{
      path: string;
      kind: string;
      bytes: number;
    }>;
    buildId: string;
    generatedAt: string;
    mode: "development" | "production";
  }
): string {
  const identity = {
    framework: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
    },
    build: {
      id: options.buildId,
      generatedAt: options.generatedAt,
      mode: options.mode,
      artifactCount: options.artifactCount,
    },
    artifacts: options.artifacts,
    site: {
      pages: site.pages.length,
      posts: site.posts.length,
    },
    runtime: {
      inspectable: true,
      normalizedManifest: true,
      agentReadable: true,
    },
  };

  return JSON.stringify(identity, null, 2);
}

export function generateLlmsText(site: SiteDefinition): string {
  const orderedPosts = sortPosts(site.posts);
  const pages = site.pages
    .map((page) => {
      const summary = page.tokenSummary
        ? ` - ${page.tokenSummary}`
        : "";
      return `- ${page.title}: ${normalizePath(page.path)}${summary}`;
    })
    .join("\n");
  const posts = orderedPosts
    .map(
      (post) =>
        `- ${post.title}: ${postPath(post)} - ${post.tokenSummary}`
    )
    .join("\n");

  return `# ${site.title}

This site is generated by Paideia Framework.

Useful agent entrypoints:
- /system.json - runtime and site contract
- /runtime.json - runtime identity and build metadata
- /context.json - compressed site map and summaries
- /llms.txt - agent guidance

## Site

${site.description}
${site.url ? `\nCanonical site URL: ${site.url}` : ""}
${site.author ? `\nAuthor: ${site.author}` : ""}
Language: ${siteLanguage(site)}

## Pages

${pages}

## Writing

${posts}

## Generated By

Paideia Framework v${FRAMEWORK_VERSION}
`;
}

export function generateContextJson(site: SiteDefinition): string {
  const orderedPosts = sortPosts(site.posts);
  const latestPost = orderedPosts[0] ?? null;

  const context = {
    site: {
      title: site.title,
      description: site.description,
      url: site.url ?? null,
      author: site.author ?? null,
      language: siteLanguage(site),
    },
    pages: site.pages.map((page) => ({
      path: normalizePath(page.path),
      canonical: canonicalUrl(site, page.path),
      title: page.title,
      description:
        page.description ?? site.description,
      tokenSummary:
        page.tokenSummary ?? page.body,
    })),
    posts: orderedPosts.map((post) => ({
      slug: post.slug,
      path: postPath(post),
      canonical: canonicalUrl(site, postPath(post)),
      title: post.title,
      publishedAt: post.publishedAt,
      tokenSummary: post.tokenSummary,
    })),
    writing: {
      postCount: orderedPosts.length,
      latestPost: latestPost?.slug ?? null,
    },
    generatedBy: {
      name: "Paideia Framework",
      version: FRAMEWORK_VERSION,
    },
  };

  return JSON.stringify(context, null, 2);
}
